"""empty message

Revision ID: 56926d53c331
Revises: 0f81ba5297fe
Create Date: 2025-06-08 00:32:16.332378

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "56926d53c331"
down_revision: Union[str, None] = "0f81ba5297fe"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column("product", "price", existing_type=sa.NUMERIC(precision=10, scale=2), nullable=False)
    op.alter_column("product", "discount_price", existing_type=sa.NUMERIC(precision=10, scale=2), nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column("product", "discount_price", existing_type=sa.NUMERIC(precision=10, scale=2), nullable=True)
    op.alter_column("product", "price", existing_type=sa.NUMERIC(precision=10, scale=2), nullable=True)
    # ### end Alembic commands ###
