"""empty message

Revision ID: be5b698b8c45
Revises: f3b3875f212c
Create Date: 2025-06-07 16:20:41.368062

"""

from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = "be5b698b8c45"
down_revision: Union[str, None] = "f3b3875f212c"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("order_item")
    op.add_column("item_out", sa.Column("order_id", sa.Integer(), nullable=False))
    op.add_column("item_out", sa.Column("count", sa.Integer(), nullable=False))
    op.create_foreign_key(
        None, "item_out", "order", ["order_id"], ["id"], ondelete="CASCADE"
    )
    op.add_column("order", sa.Column("sold_datetime", sa.DateTime(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("order", "sold_datetime")
    op.drop_constraint(None, "item_out", type_="foreignkey")
    op.drop_column("item_out", "count")
    op.drop_column("item_out", "order_id")
    op.create_table(
        "order_item",
        sa.Column("item_out_id", sa.INTEGER(), autoincrement=False, nullable=False),
        sa.Column("order_id", sa.INTEGER(), autoincrement=False, nullable=False),
        sa.Column(
            "sold_datetime", postgresql.TIMESTAMP(), autoincrement=False, nullable=False
        ),
        sa.Column("id", sa.INTEGER(), autoincrement=True, nullable=False),
        sa.ForeignKeyConstraint(
            ["item_out_id"],
            ["item_out.id"],
            name=op.f("order_item_item_out_id_fkey"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["order_id"],
            ["order.id"],
            name=op.f("order_item_order_id_fkey"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("order_item_pkey")),
    )
    # ### end Alembic commands ###
