services:
  fastapi_app:
    build: 
      dockerfile: ./Dockerfile
    container_name: e-com_product_api
    command: sh -c "uvicorn src.main:app --reload --port=8000 --host=0.0.0.0"
    env_file:
      - .env
    ports:
      - '8001:8000'
    depends_on:
      database:
       condition: service_healthy

  database:
    image: postgres:16-alpine3.19
    container_name: e-com_product_postgres
    env_file:
      - .env
    volumes:
      - './postgres_data:/var/lib/postgresql/data'
    restart: unless-stopped
    ports:
      - "5432:5432"
    healthcheck:
      test: ["CMD-SHELL", "sh -c 'pg_isready -U ${POSTGRES_USER} -d ${POSTGRES_DB}'"]
      interval: 4s
      timeout: 5s
      retries: 5
