name: Backend Contnious integration

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  backend-integration-ci:
    runs-on: ubuntu-latest

    services:
      postgres:
        image: postgres:16-alpine
        env:
          POSTGRES_DB: ${{ secrets.POSTGRES_DB }}
          POSTGRES_USER: ${{ secrets.POSTGRES_USER }}
          POSTGRES_PASSWORD: ${{ secrets.POSTGRES_PASSWORD }}
        ports:
          - 5432:5432
        options: >-
          --health-cmd="pg_isready -U postgres"
          --health-interval=5s
          --health-timeout=5s
          --health-retries=5

    steps:
      - uses: actions/checkout@v4

      - name: Создать .env с секретами для products
        run: |
          export POSTGRES_USER="${{ secrets.POSTGRES_USER }}"
          export POSTGRES_PASSWORD="${{ secrets.POSTGRES_PASSWORD }}"
          export POSTGRES_DB="${{ secrets.POSTGRES_DB }}"
          export POSTGRES_PORT=5433
          envsubst < backend/products/.env.example > backend/products/.env

      - name: Создать .env с секретами для users
        run: |
          export POSTGRES_USER="${{ secrets.POSTGRES_USER }}"
          export POSTGRES_PASSWORD="${{ secrets.POSTGRES_PASSWORD }}"
          export POSTGRES_DB="${{ secrets.POSTGRES_DB }}"
          export POSTGRES_PORT=5434
          export JWT_SECRET_KEY="${{ secrets.JWT_SECRET_KEY }}"
          export ACCESS_TOKEN_EXPIRE_SECONDS="${{ secrets.ACCESS_TOKEN_EXPIRE_SECONDS }}"
          export REFRESH_TOKEN_EXPIRE_SECONDS="${{ secrets.REFRESH_TOKEN_EXPIRE_SECONDS }}"
          envsubst < backend/users/.env.example > backend/users/.env

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Build and start all backend services
        run: |
          docker compose -f backend/products/docker-compose.yml up -d --build
          docker compose -f backend/users/docker-compose.yml up -d --build

      - name: Wait for services to be healthy
        run: sleep 20

      - name: Stop all services
        if: always()
        run: |
          docker compose -f backend/products/docker-compose.yml down -v
          docker compose -f backend/users/docker-compose.yml down -v