"""empty message

Revision ID: 638fa128652e
Revises: d83193f10b11
Create Date: 2025-06-07 15:00:00.205031

"""

from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op


# revision identifiers, used by Alembic.
revision: str = "638fa128652e"
down_revision: Union[str, None] = "d83193f10b11"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("users", sa.Column("bank_name", sa.String(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("users", "bank_name")
    # ### end Alembic commands ###
