"""empty message

Revision ID: d83193f10b11
Revises: 4e57f5f356bc
Create Date: 2025-06-07 13:23:23.181974

"""

from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op


# revision identifiers, used by Alembic.
revision: str = "d83193f10b11"
down_revision: Union[str, None] = "4e57f5f356bc"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "users", sa.Column("name", sa.String(length=100), nullable=False)
    )
    op.add_column(
        "users", sa.Column("inn", sa.String(length=12), nullable=False)
    )
    op.add_column(
        "users", sa.Column("card_number", sa.String(length=20), nullable=False)
    )
    op.add_column(
        "users", sa.Column("bank_code", sa.String(length=9), nullable=False)
    )
    op.add_column(
        "users",
        sa.Column("phone_number", sa.String(length=18), nullable=False),
    )
    op.alter_column(
        "users", "username", existing_type=sa.VARCHAR(), nullable=False
    )
    op.alter_column(
        "users", "email", existing_type=sa.VARCHAR(), nullable=False
    )
    op.alter_column(
        "users", "hashed_password", existing_type=sa.VARCHAR(), nullable=False
    )
    op.alter_column(
        "users", "is_active", existing_type=sa.BOOLEAN(), nullable=False
    )
    op.create_unique_constraint(None, "users", ["inn"])
    op.create_unique_constraint(None, "users", ["phone_number"])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, "users", type_="unique")
    op.drop_constraint(None, "users", type_="unique")
    op.alter_column(
        "users", "is_active", existing_type=sa.BOOLEAN(), nullable=True
    )
    op.alter_column(
        "users", "hashed_password", existing_type=sa.VARCHAR(), nullable=True
    )
    op.alter_column(
        "users", "email", existing_type=sa.VARCHAR(), nullable=True
    )
    op.alter_column(
        "users", "username", existing_type=sa.VARCHAR(), nullable=True
    )
    op.drop_column("users", "phone_number")
    op.drop_column("users", "bank_code")
    op.drop_column("users", "card_number")
    op.drop_column("users", "inn")
    op.drop_column("users", "name")
    # ### end Alembic commands ###
